/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#615e55',
        'typewriter-ribbon': '#34332F',
        'outline-variant': '#49473f',
        'surface-tint': '#cbc6bb',
        'secondary-container': '#822621',
        'on-primary-fixed': '#1d1c14',
        'lead-charcoal': '#101010',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#4a454b',
        'error': '#ffb4ab',
        'on-primary-fixed-variant': '#49473e',
        'carbon-gray': '#171717',
        'on-surface-variant': '#cac6bc',
        'on-error': '#690005',
        'on-secondary': '#630f0e',
        'verification-green': '#55785A',
        'primary-fixed': '#e7e2d6',
        'secondary': '#ffb4ab',
        'on-primary': '#323028',
        'surface-container': '#201f1f',
        'on-secondary-fixed-variant': '#822621',
        'on-background': '#e5e2e1',
        'outline': '#949087',
        'tertiary-fixed': '#e8e0e7',
        'inverse-surface': '#e5e2e1',
        'paper-aged': '#E9E4D8',
        'on-tertiary': '#332f34',
        'primary-fixed-dim': '#cbc6bb',
        'secondary-fixed': '#ffdad6',
        'inverse-on-surface': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-container': '#686369',
        'on-secondary-fixed': '#410002',
        'tertiary-container': '#e8e0e7',
        'primary': '#ffffff',
        'on-secondary-container': '#ff998f',
        'surface-container-low': '#1c1b1b',
        'secondary-fixed-dim': '#ffb4ab',
        'surface-variant': '#353534',
        'primary-container': '#e7e2d6',
        'on-tertiary-fixed': '#1e1a1f',
        'surface-container-highest': '#353534',
        'tertiary-fixed-dim': '#ccc4cb',
        'background': '#131313',
        'on-primary-container': '#67645b',
        'on-surface': '#e5e2e1',
        'surface': '#131313',
        'error-container': '#93000a',
        'ink-red': '#8F302A',
        'on-error-container': '#ffdad6',
        'tertiary': '#ffffff',
        'surface-bright': '#3a3939',
        'surface-dim': '#131313',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-mobile': '20px',
        gutter: '16px',
        'container-max': '1200px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Special Elite', 'serif'],
        'metadata-xs': ['DM Mono', 'monospace'],
        'label-caps': ['DM Mono', 'monospace'],
        'stamp-lg': ['Special Elite', 'serif'],
        'headline-lg': ['Special Elite', 'serif'],
        'display-lg': ['Special Elite', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'technical-sm': ['DM Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '400' }],
        'metadata-xs': ['10px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '700' }],
        'stamp-lg': ['24px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.1', fontWeight: '400' }],
        'display-lg': ['84px', { lineHeight: '1.0', letterSpacing: '-0.02em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'technical-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
